config/routes.rb
Rails.application.routes.draw do
  resources :trends
  resources :articles

  root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true

  include PgSearch::Model
  pg_search_scope :pg_search,
                  against: %i[title body],
                  using: {
                    tsearch: { dictionary: 'english' }
                  }

  def self.search(search)
    return all unless search.present?

    pg_search(search)
  end
end

app/models/trend.rb
class Trend < ApplicationRecord
  validates :session_id, presence: true
  validates :search, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show]
  before_action :validate_session, only: [:index]

  # GET /articles or /articles.json
  def index
    @articles = Article.search(params[:search]).page(params[:page]).without_count.per(4)

    if turbo_frame_request?
      render(partial: 'articles', locals: { articles: @articles })
    else
      render :index
    end
    save_trend(session[:user_id], params[:search]) if params[:search].present?
  end

  # GET /articles/1 or /articles/1.json
  def show; end

  def save_trend(session_id, search)
    return unless search.length > 2

    @latest_trend = Trend.new(trend_params)
    @latest_trend.session_id = session_id
    session_trends = Trend.where(session_id:)

    # Update previous searches or save if new
    @latest_trend.save if session_trends.empty?
    data_count = 0
    while data_count < session_trends.length && (session_trends[data_count].search.to_s.similar search.to_s) < 0.50
      data_count += 1
    end
    data_count < session_trends.length ? session_trends[data_count].update(search:) : @latest_trend.save
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def article_params
    params.require(:article).permit(:title, :body)
  end

  def trend_params
    params.permit(:search)
  end

  def validate_session
    session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  end
end

app/controllers/trends_controller.rb
class TrendsController < ApplicationController
  # GET /trends or /trends.json
  def index
    @trends_array = Trend.group(:id).map { |t| t.search }

    # Sort in descending order
    @sorted_trends = @trends_array.sort_by(&:first)

    # Group and count
    @trends = (@sorted_trends.inject(Hash.new(0)) do |total, e|
                 total[e] += 1
                 total
               end).first(10)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_articles.html.erb
<%= turbo_frame_tag "articles" do %>
  <% @articles.each do |article| %>
    <strong>
      <%= link_to article.title, article_path(article) %>
    </strong>

    <p class="article-body">
      <%= link_to truncate(article.body, :length => 200), article_path(article) %>
      <hr>
    </p>
  <% end %>

  <div class="pagination">
    <%= link_to_prev_page @articles, 'Previous Page', class: "links" %>
    <%= link_to_next_page @articles, 'Next Page', class: "links" %>
  </div>
<% end %>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Welcome. How Can We Help?</h1>

<%= form_with(url: articles_path, method: :get, data: { controller: "search-form", turbo_frame: "articles"}) do |f| %>
  <div class="form-top">
    <%= f.text_field :search, value:params[:search], autocomplete:"off", placeholder: "Search articles", data: { action: "input->search-form#search" } %>
    <%= f.submit "Search", id: "btn-submit" %>
    <%= link_to "Show Searches", trends_path, class: "links", id:"btn-show-searches"%>
  </div>
<% end %>

<div id="articles">
  <% if @articles.empty? %>
    <p>No result...</p>
    <small>Tip: Search lengthy full english words to get correct results.</small>
  <% else %>
    <%= render partial: "articles", locals: { articles: @articles } %>
  <% end %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<div id="<%= dom_id @article %>">
  <p>
    <h1>Title:
    <%= @article.title %>
    </h1>
  </p>

  <p class="body-text">
    <%= @article.body %>
  </p>

</div>

<div>
  <%= link_to "Back To Articles", articles_path, class: "links" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knowledgebase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trends/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Most searched words</h1>

<div id="trends">
  <% @trends.each do |trend, count| %>
    <p>
      "<%= trend %>" searched <%= count %> <%= count > 1 ? "times" : "time" %>
    </p>
    <hr class="hr-right" >
  <% end %>
</div>

<div>
  <%= link_to "Back to articles", articles_path, class: "links" %>
</div>